custom: ['donate.https://sites.google.com/view/zink-bot/home?pli=1.dev', 'discord.gg/dcdev', 'bero.https://sites.google.com/view/zink-bot/home?pli=1.dev', 'bittmax.https://sites.google.com/view/zink-bot/home?pli=1.dev' ]
